version: '3'

services:
  db:
    container_name: my-dbtest
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:latest
    restart: unless-stopped

  pgadmin:
    container_name: pg-admintest
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadmin_email}
      - PGADMIN_DEFAULT_PASSWORD=${pgadmin_pass}
    image: dpage/pgadmin4:latest

  strapi:
    container_name: my-apptest
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=${strapi_client}
      - DATABASE_HOST=${strapi_host}
      - DATABASE_PORT=${strapi_port}
      - DATABASE_NAME=${strapi_name}
      - DATABASE_USERNAME=${strapi_username}
      - DATABASE_PASSWORD=${strapi_pass}
      - DATABASE_SSL=${strapi_ssl}
    image: naskio/strapi:latest

    ##docker-compose up อัพ down ปิด